MAIN_PAGE = "https://stellarburgers.nomoreparties.site/"
LOGIN_PAGE = f"{MAIN_PAGE}login"
FORGOT_PASSWORD_PAGE = f"{MAIN_PAGE}forgot-password"
RESET_PASSWORD_PAGE = f"{MAIN_PAGE}reset-password"
REGISTER_PAGE = f"{MAIN_PAGE}register"
ACCOUNT_PAGE = f"{MAIN_PAGE}account"
ORDER_HISTORY_PAGE = f"{ACCOUNT_PAGE}/order-history"